quarkus.http.port=8080
cc
# Kafka - valeur utilisée uniquement en prod/Docker
# En mode dev, Quarkus démarre automatiquement un Kafka embarqué
%prod.kafka.bootstrap.servers=${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}

mp.messaging.outgoing.messages-out.connector=smallrye-kafka
mp.messaging.outgoing.messages-out.topic=${KAFKA_TOPIC:demo-topic}
mp.messaging.outgoing.messages-out.key.serializer=org.apache.kafka.common.serialization.StringSerializer
mp.messaging.outgoing.messages-out.value.serializer=org.apache.kafka.common.serialization.StringSerializer

# Logs
quarkus.log.category."org.apache.kafka".level=INFO
quarkus.log.category."io.smallrye.reactive.messaging".level=INFO
